import { Gym } from './types';

export const GYMS: Gym[] = [
  // ── Texas ─────────────────────────────────────────────────────
  {
    id: '1',
    name: 'Gracie Barra Austin',
    address: '4301 W William Cannon Dr #B105',
    city: 'Austin',
    state: 'TX',
    country: 'US',
    lat: 30.2240,
    lng: -97.8016,
    website: 'https://graciebarra.com',
    open_mats: [
      { id: '1-1', discipline: 'gi_bjj',   day: 'saturday', start_time: '10:00', end_time: '12:00', is_free: true },
      { id: '1-2', discipline: 'nogi_bjj', day: 'sunday',   start_time: '11:00', end_time: '13:00', is_free: true },
    ],
  },
  {
    id: '2',
    name: 'Atos Jiu-Jitsu Austin',
    address: '5555 N Lamar Blvd Suite L-130',
    city: 'Austin',
    state: 'TX',
    country: 'US',
    lat: 30.3289,
    lng: -97.7357,
    open_mats: [
      { id: '2-1', discipline: 'nogi_bjj', day: 'saturday', start_time: '11:00', end_time: '13:00', is_free: false, cost: 20 },
    ],
  },
  {
    id: '3',
    name: 'Alliance MMA Houston',
    address: '9659 Katy Freeway Suite 300',
    city: 'Houston',
    state: 'TX',
    country: 'US',
    lat: 29.7878,
    lng: -95.5554,
    open_mats: [
      { id: '3-1', discipline: 'gi_bjj',   day: 'saturday', start_time: '10:00', end_time: '12:00', is_free: true },
      { id: '3-2', discipline: 'mma',      day: 'sunday',   start_time: '12:00', end_time: '14:00', is_free: false, cost: 15 },
    ],
  },
  // ── California ───────────────────────────────────────────────
  {
    id: '4',
    name: '10th Planet Jiu Jitsu HQ',
    address: '800 S Central Ave',
    city: 'Los Angeles',
    state: 'CA',
    country: 'US',
    lat: 34.0429,
    lng: -118.2590,
    website: 'https://10thplanetjj.com',
    open_mats: [
      { id: '4-1', discipline: 'nogi_bjj', day: 'saturday', start_time: '12:00', end_time: '14:00', is_free: true },
      { id: '4-2', discipline: 'nogi_bjj', day: 'sunday',   start_time: '12:00', end_time: '14:00', is_free: true },
    ],
  },
  {
    id: '5',
    name: 'Atos Jiu-Jitsu San Diego',
    address: '5060 Shoreham Place Suite 100',
    city: 'San Diego',
    state: 'CA',
    country: 'US',
    lat: 32.8730,
    lng: -117.2159,
    open_mats: [
      { id: '5-1', discipline: 'nogi_bjj', day: 'saturday', start_time: '11:00', end_time: '13:00', is_free: false, cost: 25 },
      { id: '5-2', discipline: 'gi_bjj',   day: 'sunday',   start_time: '10:00', end_time: '12:00', is_free: false, cost: 20 },
    ],
  },
  {
    id: '6',
    name: 'Gracie Barra San Francisco',
    address: '3221 20th St',
    city: 'San Francisco',
    state: 'CA',
    country: 'US',
    lat: 37.7586,
    lng: -122.4195,
    open_mats: [
      { id: '6-1', discipline: 'gi_bjj',   day: 'saturday', start_time: '10:00', end_time: '11:30', is_free: true },
    ],
  },
  // ── New York ─────────────────────────────────────────────────
  {
    id: '7',
    name: 'Renzo Gracie Academy NYC',
    address: '224 W 30th St',
    city: 'New York',
    state: 'NY',
    country: 'US',
    lat: 40.7487,
    lng: -73.9945,
    website: 'https://renzogracie.com',
    open_mats: [
      { id: '7-1', discipline: 'gi_bjj',   day: 'saturday', start_time: '12:00', end_time: '14:00', is_free: false, cost: 30 },
      { id: '7-2', discipline: 'nogi_bjj', day: 'sunday',   start_time: '12:00', end_time: '14:00', is_free: false, cost: 30 },
    ],
  },
  {
    id: '8',
    name: 'Atlas BJJ Brooklyn',
    address: '348 Myrtle Ave',
    city: 'Brooklyn',
    state: 'NY',
    country: 'US',
    lat: 40.6950,
    lng: -73.9677,
    open_mats: [
      { id: '8-1', discipline: 'nogi_bjj', day: 'saturday', start_time: '11:00', end_time: '13:00', is_free: true },
      { id: '8-2', discipline: 'wrestling', day: 'friday',  start_time: '19:00', end_time: '20:30', is_free: false, cost: 15 },
    ],
  },
  // ── Florida ──────────────────────────────────────────────────
  {
    id: '9',
    name: 'American Top Team Coconut Creek',
    address: '5070 Coconut Creek Pkwy',
    city: 'Coconut Creek',
    state: 'FL',
    country: 'US',
    lat: 26.2713,
    lng: -80.1697,
    website: 'https://americantopteam.com',
    open_mats: [
      { id: '9-1', discipline: 'mma',      day: 'saturday', start_time: '11:00', end_time: '13:00', is_free: false, cost: 20 },
      { id: '9-2', discipline: 'nogi_bjj', day: 'saturday', start_time: '13:00', end_time: '15:00', is_free: false, cost: 20 },
    ],
  },
  {
    id: '10',
    name: 'Ground Game Theory Miami',
    address: '10901 NW 17th St Suite 101',
    city: 'Miami',
    state: 'FL',
    country: 'US',
    lat: 25.7895,
    lng: -80.3284,
    website: 'https://groundgametheory.com',
    open_mats: [
      { id: '10-1', discipline: 'nogi_bjj', day: 'saturday', start_time: '11:00', end_time: '13:00', is_free: true },
      { id: '10-2', discipline: 'nogi_bjj', day: 'sunday',   start_time: '13:30', end_time: '15:30', is_free: true },
    ],
  },
  // ── Illinois ─────────────────────────────────────────────────
  {
    id: '11',
    name: 'Midwest BJJ Chicago',
    address: '1831 W 21st St',
    city: 'Chicago',
    state: 'IL',
    country: 'US',
    lat: 41.8532,
    lng: -87.6730,
    open_mats: [
      { id: '11-1', discipline: 'gi_bjj',   day: 'saturday', start_time: '10:00', end_time: '12:00', is_free: true },
      { id: '11-2', discipline: 'nogi_bjj', day: 'sunday',   start_time: '11:00', end_time: '13:00', is_free: true },
    ],
  },
  {
    id: '12',
    name: 'Muay Thai Chicago',
    address: '2200 N Lincoln Ave',
    city: 'Chicago',
    state: 'IL',
    country: 'US',
    lat: 41.9219,
    lng: -87.6461,
    open_mats: [
      { id: '12-1', discipline: 'muay_thai', day: 'saturday', start_time: '10:00', end_time: '12:00', is_free: false, cost: 20 },
      { id: '12-2', discipline: 'boxing',    day: 'sunday',   start_time: '10:00', end_time: '12:00', is_free: false, cost: 15 },
    ],
  },
  // ── Colorado ─────────────────────────────────────────────────
  {
    id: '13',
    name: 'Easton Training Center Denver',
    address: '3250 N Uinta St',
    city: 'Denver',
    state: 'CO',
    country: 'US',
    lat: 39.7674,
    lng: -104.9154,
    website: 'https://eastoncenter.com',
    open_mats: [
      { id: '13-1', discipline: 'gi_bjj',   day: 'saturday', start_time: '11:00', end_time: '13:00', is_free: true },
      { id: '13-2', discipline: 'muay_thai', day: 'saturday', start_time: '09:00', end_time: '11:00', is_free: false, cost: 20 },
    ],
  },
  // ── Nevada ───────────────────────────────────────────────────
  {
    id: '14',
    name: 'Syndicate MMA Las Vegas',
    address: '4300 Meadows Ln',
    city: 'Las Vegas',
    state: 'NV',
    country: 'US',
    lat: 36.1655,
    lng: -115.2214,
    open_mats: [
      { id: '14-1', discipline: 'mma',      day: 'saturday', start_time: '10:00', end_time: '12:00', is_free: false, cost: 25 },
      { id: '14-2', discipline: 'boxing',   day: 'saturday', start_time: '08:00', end_time: '10:00', is_free: false, cost: 20 },
    ],
  },
  // ── Georgia ──────────────────────────────────────────────────
  {
    id: '15',
    name: 'Buckhead Jiu Jitsu Atlanta',
    address: '1920 Howell Mill Rd NW',
    city: 'Atlanta',
    state: 'GA',
    country: 'US',
    lat: 33.7946,
    lng: -84.4086,
    open_mats: [
      { id: '15-1', discipline: 'gi_bjj',   day: 'sunday',   start_time: '11:00', end_time: '13:00', is_free: true },
      { id: '15-2', discipline: 'nogi_bjj', day: 'saturday', start_time: '10:00', end_time: '12:00', is_free: true },
    ],
  },
  // ── Washington ───────────────────────────────────────────────
  {
    id: '16',
    name: 'Seattle Judo & BJJ',
    address: '2205 5th Ave',
    city: 'Seattle',
    state: 'WA',
    country: 'US',
    lat: 47.6148,
    lng: -122.3522,
    open_mats: [
      { id: '16-1', discipline: 'judo',     day: 'saturday', start_time: '10:00', end_time: '12:00', is_free: true },
      { id: '16-2', discipline: 'gi_bjj',   day: 'sunday',   start_time: '10:00', end_time: '12:00', is_free: true },
    ],
  },
  // ── Massachusetts ────────────────────────────────────────────
  {
    id: '17',
    name: 'Boston BJJ',
    address: '561 Windsor St',
    city: 'Boston',
    state: 'MA',
    country: 'US',
    lat: 42.3513,
    lng: -71.1089,
    open_mats: [
      { id: '17-1', discipline: 'nogi_bjj', day: 'sunday',   start_time: '12:00', end_time: '14:00', is_free: true },
      { id: '17-2', discipline: 'wrestling', day: 'saturday', start_time: '09:00', end_time: '11:00', is_free: false, cost: 15 },
    ],
  },
  // ── Pennsylvania ─────────────────────────────────────────────
  {
    id: '18',
    name: 'Warrior Way BJJ Philadelphia',
    address: '4101 Whitaker Ave',
    city: 'Philadelphia',
    state: 'PA',
    country: 'US',
    lat: 40.0259,
    lng: -75.1224,
    open_mats: [
      { id: '18-1', discipline: 'gi_bjj',   day: 'saturday', start_time: '11:00', end_time: '13:00', is_free: true },
      { id: '18-2', discipline: 'kickboxing', day: 'sunday', start_time: '10:00', end_time: '12:00', is_free: false, cost: 15 },
    ],
  },
  // ── Arizona ──────────────────────────────────────────────────
  {
    id: '19',
    name: 'Arizona Combat Sports Phoenix',
    address: '1616 W Camelback Rd',
    city: 'Phoenix',
    state: 'AZ',
    country: 'US',
    lat: 33.5093,
    lng: -112.0858,
    open_mats: [
      { id: '19-1', discipline: 'mma',      day: 'saturday', start_time: '09:00', end_time: '11:00', is_free: false, cost: 20 },
      { id: '19-2', discipline: 'muay_thai', day: 'sunday',  start_time: '10:00', end_time: '12:00', is_free: false, cost: 20 },
    ],
  },
  // ── Minnesota ────────────────────────────────────────────────
  {
    id: '20',
    name: 'Minnesota Martial Arts Academy Minneapolis',
    address: '3008 Hennepin Ave S',
    city: 'Minneapolis',
    state: 'MN',
    country: 'US',
    lat: 44.9338,
    lng: -93.2974,
    open_mats: [
      { id: '20-1', discipline: 'gi_bjj',   day: 'saturday', start_time: '10:30', end_time: '12:30', is_free: true },
      { id: '20-2', discipline: 'wrestling', day: 'saturday', start_time: '08:00', end_time: '10:00', is_free: true },
    ],
  },
  // ── Europe ───────────────────────────────────────────────────
  {
    id: '21',
    name: 'Roger Gracie Academy London',
    address: '160 Greyhound Rd',
    city: 'London',
    state: 'England',
    country: 'UK',
    lat: 51.4821,
    lng: -0.2017,
    website: 'https://rogergracie.com',
    open_mats: [
      { id: '21-1', discipline: 'gi_bjj',   day: 'saturday', start_time: '12:00', end_time: '14:00', is_free: false, cost: 15 },
      { id: '21-2', discipline: 'nogi_bjj', day: 'sunday',   start_time: '12:00', end_time: '14:00', is_free: false, cost: 15 },
    ],
  },
  {
    id: '22',
    name: 'SBG Ireland Dublin',
    address: '24 Kylemore Rd',
    city: 'Dublin',
    state: 'Leinster',
    country: 'IE',
    lat: 53.3354,
    lng: -6.3312,
    open_mats: [
      { id: '22-1', discipline: 'mma',      day: 'saturday', start_time: '11:00', end_time: '13:00', is_free: false, cost: 10 },
      { id: '22-2', discipline: 'nogi_bjj', day: 'sunday',   start_time: '11:00', end_time: '13:00', is_free: false, cost: 10 },
    ],
  },
  {
    id: '23',
    name: 'Flow Jiu Jitsu Amsterdam',
    address: 'Spaarndammerdijk 302',
    city: 'Amsterdam',
    state: 'Noord-Holland',
    country: 'NL',
    lat: 52.3933,
    lng: 4.8811,
    open_mats: [
      { id: '23-1', discipline: 'nogi_bjj', day: 'saturday', start_time: '12:00', end_time: '14:00', is_free: true },
    ],
  },
  {
    id: '24',
    name: 'Berlin BJJ',
    address: 'Bergmannstraße 68',
    city: 'Berlin',
    state: 'Berlin',
    country: 'DE',
    lat: 52.4907,
    lng: 13.3933,
    open_mats: [
      { id: '24-1', discipline: 'gi_bjj',   day: 'saturday', start_time: '13:00', end_time: '15:00', is_free: false, cost: 10 },
      { id: '24-2', discipline: 'nogi_bjj', day: 'sunday',   start_time: '12:00', end_time: '14:00', is_free: false, cost: 10 },
    ],
  },
  {
    id: '25',
    name: 'Gracie Barra Barcelona',
    address: 'Carrer de Pallars 95',
    city: 'Barcelona',
    state: 'Catalonia',
    country: 'ES',
    lat: 41.3994,
    lng: 2.1956,
    open_mats: [
      { id: '25-1', discipline: 'gi_bjj',   day: 'saturday', start_time: '11:00', end_time: '13:00', is_free: false, cost: 10 },
    ],
  },
  {
    id: '26',
    name: 'Combat Academy Paris',
    address: '47 Rue de Montreuil',
    city: 'Paris',
    state: 'Île-de-France',
    country: 'FR',
    lat: 48.8530,
    lng: 2.3928,
    open_mats: [
      { id: '26-1', discipline: 'muay_thai', day: 'saturday', start_time: '10:00', end_time: '12:00', is_free: false, cost: 15 },
      { id: '26-2', discipline: 'kickboxing', day: 'sunday',  start_time: '10:00', end_time: '12:00', is_free: false, cost: 12 },
    ],
  },
  {
    id: '27',
    name: 'Stockholm Judo & BJJ',
    address: 'Ringvägen 100',
    city: 'Stockholm',
    state: 'Stockholm County',
    country: 'SE',
    lat: 59.3098,
    lng: 18.0739,
    open_mats: [
      { id: '27-1', discipline: 'judo',     day: 'saturday', start_time: '10:00', end_time: '12:00', is_free: false, cost: 8 },
      { id: '27-2', discipline: 'gi_bjj',   day: 'saturday', start_time: '12:00', end_time: '14:00', is_free: false, cost: 8 },
    ],
  },
  // ── More US gyms ─────────────────────────────────────────────
  {
    id: '28',
    name: 'Crucible MMA Portland',
    address: '219 SW Stark St',
    city: 'Portland',
    state: 'OR',
    country: 'US',
    lat: 45.5225,
    lng: -122.6789,
    open_mats: [
      { id: '28-1', discipline: 'nogi_bjj', day: 'saturday', start_time: '11:00', end_time: '13:00', is_free: true },
      { id: '28-2', discipline: 'mma',      day: 'sunday',   start_time: '11:00', end_time: '13:00', is_free: false, cost: 20 },
    ],
  },
  {
    id: '29',
    name: 'Triangle Jiu Jitsu Raleigh',
    address: '4604 Hillsborough Rd',
    city: 'Raleigh',
    state: 'NC',
    country: 'US',
    lat: 35.8205,
    lng: -78.6944,
    open_mats: [
      { id: '29-1', discipline: 'gi_bjj',   day: 'saturday', start_time: '10:00', end_time: '12:00', is_free: true },
    ],
  },
  {
    id: '30',
    name: 'Jackson-Wink MMA Academy',
    address: '4121 Cutler Ave NE',
    city: 'Albuquerque',
    state: 'NM',
    country: 'US',
    lat: 35.1264,
    lng: -106.5888,
    open_mats: [
      { id: '30-1', discipline: 'mma',      day: 'saturday', start_time: '10:00', end_time: '12:00', is_free: false, cost: 30 },
      { id: '30-2', discipline: 'wrestling', day: 'saturday', start_time: '08:00', end_time: '10:00', is_free: false, cost: 20 },
    ],
  },
];
